package org.musetest.core.step;

import org.musetest.core.*;
import org.musetest.core.context.*;
import org.musetest.core.events.*;
import org.musetest.core.steptest.*;
import org.slf4j.*;

/**
 * @author Christopher L Merrill (see LICENSE.txt for license details)
 */
public class StepExecutor
    {
    public StepExecutor(ContainsStep step, StepsExecutionContext context)
        {
        _context = context;

        _context.addEventListener(_log);
        _context.addEventListener(new TerminateOnError(this));
        _context.getExecutionStack().push(new SingleStepExecutionContext(_context, step.getStep(), true));
        }

    public void executeAll()
        {
        boolean had_a_step_to_run = true;
        while (had_a_step_to_run && !_terminate)
            had_a_step_to_run = executeNextStep();
        }

    /**
     * @return false if there are no more steps to run.
     */
    public boolean executeNextStep()
        {
        if (!_context.getExecutionStack().hasMoreSteps())
            return false;

        StepExecutionContext step_context = _context.getExecutionStack().peek();
        String error_message = null;
        StepExecutionResult step_result = null;
        MuseStep step = null;

        _context.raiseEvent(new StepEvent(MuseEventType.StartStep, step_context.getCurrentStepConfiguration(), step_context));
        try
            {
            step = step_context.getCurrentStep();
            step_result = step.execute(step_context);
            }
        catch (StepConfigurationError error)
            {
            error_message = "step error due to configuration problem: " + error.getMessage();
            }
        catch (StepExecutionError error)
            {
            error_message = "step failed to execute: " + error.getMessage();
            }
        catch (Throwable t)
            {
            LOG.error("Unexpected error caught while executing step", t);
            error_message = "cannot execute the step due to an unexpected error: " + t.getMessage();
            }

        StepConfiguration step_config;
        if (step != null)
            step_config = step.getConfiguration();
        else
            step_config = step_context.getCurrentStepConfiguration();

        if (error_message != null) // if the step did not complete normally, the EndStep event needs to be generated here, since it likely was not generated by the step itself.
            {
            step_result = new BasicStepExecutionResult(StepExecutionStatus.ERROR, error_message);
            if (step_config != null)
                _context.raiseEvent(new StepEvent(MuseEventType.EndStep, step_config, step_context, step_result));
            }
        if (step != null && !step_result.getStatus().equals(StepExecutionStatus.INCOMPLETE))
            step_context.stepComplete(step, step_result);

        return true;
        }

    public StepConfiguration getNextStep()
        {
        if (_context.getExecutionStack().hasMoreSteps())
            return _context.getExecutionStack().peek().getCurrentStepConfiguration();
        return null;
        }

    @SuppressWarnings("WeakerAccess")  // used in GUI
    public void requestTerminate()
        {
        _terminate = true;
        }

    public EventLog getEventLog()
        {
        return _log;
        }

    private StepsExecutionContext _context;
    private boolean _terminate = false;
    private final EventLog _log = new EventLog();

    private final static Logger LOG = LoggerFactory.getLogger(StepExecutor.class);
    }


